begin;
set local lock_timeout='3s';
set local statement_timeout='30s';
select pg_advisory_xact_lock(hashtextextended('market_data_remediation_20261008_source_worker',0));

-- The coordinator seeds a finite queue. This worker has no ability to enqueue work,
-- modify original source tables, alter research objects, or create schedules.
create table if not exists market_governance.remediation_source_batch_v1 (
 batch_id bigint generated by default as identity primary key,
 run_id text not null references market_governance.remediation_run_v1(run_id),
 batch_key text not null,
 finding_ids text[] not null default '{}',
 provider text not null check(provider in ('coinbase','binance_archive','twelvedata','massive')),
 source_type text not null check(source_type in ('coinbase_candles','binance_klines','binance_mark','binance_index','binance_metrics','binance_funding','binance_book_depth','twelvedata_candles','massive_candles')),
 symbol text not null check(length(symbol) between 1 and 100 and symbol !~ '[[:cntrl:]]'),
 instrument_id uuid,
 start_ts timestamptz not null,
 end_ts timestamptz not null,
 interval_seconds integer not null check(interval_seconds in (0,60,300,600,900,1800,3600,14400,21600,86400)),
 request_json jsonb not null default '{}'::jsonb,
 status text not null default 'QUEUED' check(status in ('QUEUED','RUNNING','RETRY','COMPLETE','SOURCE_INVALID','BLOCKED','FAILED','CANCELLED')),
 priority integer not null default 0,
 attempts integer not null default 0 check(attempts between 0 and 3),
 not_before timestamptz not null default now(),
 worker_id text, lease_token uuid, lease_expires_at timestamptz, heartbeat_at timestamptz,
 current_source_id uuid,
 acquired_count bigint not null default 0, valid_count bigint not null default 0,
 invalid_count bigint not null default 0, duplicate_count bigint not null default 0,
 outside_count bigint not null default 0,
 validation jsonb not null default '{}'::jsonb,
 attempt_history jsonb not null default '[]'::jsonb check(jsonb_typeof(attempt_history)='array' and jsonb_array_length(attempt_history)<=3),
 last_error jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz,
 unique(run_id,batch_key),
 check(run_id='market_data_remediation_20261008_v1'),
 check(start_ts<end_ts and end_ts<='2026-08-01T00:00:00Z'),
 check(start_ts>='2025-09-01T00:00:00Z' or request_json ? 'warmup_contract'),
 check(end_ts-start_ts<=interval '31 days'),
 check((source_type in ('binance_funding','binance_book_depth') and interval_seconds=0) or (source_type not in ('binance_funding','binance_book_depth') and interval_seconds>0)),
 check((provider='coinbase' and source_type='coinbase_candles') or
       (provider='binance_archive' and source_type like 'binance_%') or
       (provider='twelvedata' and source_type='twelvedata_candles') or
       (provider='massive' and source_type='massive_candles')),
 check(provider<>'coinbase' or end_ts-start_ts<=interval_seconds*300*interval '1 second'),
 check(provider<>'twelvedata' or end_ts-start_ts<=interval '3 days')
);
create index if not exists remediation_source_batch_v1_claim_idx on market_governance.remediation_source_batch_v1(run_id,status,not_before,priority desc,batch_id);

create table if not exists market_governance.remediation_source_response_v1 (
 source_id uuid primary key,
 batch_id bigint not null references market_governance.remediation_source_batch_v1(batch_id),
 role text not null check(role in ('primary','checksum','error')),
 source_url text not null,
 http_status integer not null check(http_status between 100 and 599),
 response_headers jsonb not null default '{}'::jsonb,
 received_at timestamptz not null,
 revision_at timestamptz,
 source_sha256 bytea not null check(octet_length(source_sha256)=32),
 stored_body_sha256 bytea not null check(octet_length(stored_body_sha256)=32),
 compressed_sha256 bytea not null check(octet_length(compressed_sha256)=32),
 original_bytes bigint not null check(original_bytes between 0 and 67108864),
 compressed_body bytea not null check(octet_length(compressed_body)<=8388608),
 storage_encoding text not null check(storage_encoding='gzip'),
 parser_version text not null,
 credential_redactions integer not null default 0 check(credential_redactions>=0),
 provenance jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 check(source_url ~ '^https://(api\.exchange\.coinbase\.com|api\.coinbase\.com|data\.binance\.vision|api\.twelvedata\.com|api\.massive\.com)/'),
 check(source_url !~* '[?&](api[_-]?key|access[_-]?token|token|secret|password)=')
);
create index if not exists remediation_source_response_v1_batch_idx on market_governance.remediation_source_response_v1(batch_id,received_at);

create or replace function market_governance.remediation_depth_bands_valid_v1(p_bands jsonb)
returns boolean language plpgsql immutable security invoker set search_path=pg_catalog as $$
declare i integer; item jsonb; expected integer; quantity numeric; notional numeric; prior_quantity numeric; prior_notional numeric;
begin
 if p_bands is null then return true; end if;
 if jsonb_typeof(p_bands)<>'array' or jsonb_array_length(p_bands)<>10 then return false; end if;
 for i in 1..10 loop
  item=p_bands->(i-1); expected=case when i<=5 then i-6 else i-5 end;
  if jsonb_typeof(item)<>'array' or jsonb_array_length(item)<>3 or (item->>0)::numeric is distinct from expected::numeric then return false; end if;
  if length(item->>1)>120 or length(item->>2)>120 or
   item->>1 !~ '^[+]?[0-9]+([.][0-9]+)?([eE][-+]?[0-9]+)?$' or
   item->>2 !~ '^[+]?[0-9]+([.][0-9]+)?([eE][-+]?[0-9]+)?$' then return false; end if;
  quantity=(item->>1)::numeric; notional=(item->>2)::numeric;
  if quantity is null or notional is null or (quantity=0)<>(notional=0) then return false; end if;
  if i between 2 and 5 and (quantity>prior_quantity or notional>prior_notional) then return false; end if;
  if i between 7 and 10 and (quantity<prior_quantity or notional<prior_notional) then return false; end if;
  prior_quantity=quantity; prior_notional=notional;
 end loop;
 return true;
exception when others then return false;
end $$;

-- Typed storage avoids retaining a second full JSON copy per observation. Source
-- type, instrument, requested calendar and parser are reached through source/batch.
-- No field below claims an observed historical publication or receipt timestamp.
create table if not exists market_governance.remediation_observation_v1 (
 source_id uuid not null references market_governance.remediation_source_response_v1(source_id),
 observed_at timestamptz not null,
 bar_end timestamptz,
 open double precision, high double precision, low double precision, close double precision,
 volume double precision, quote_volume double precision, trade_count bigint,
 vwap double precision, taker_buy_base_volume double precision, taker_buy_quote_volume double precision,
 open_interest_quantity double precision, open_interest_quote double precision,
 global_account_long_short_ratio double precision, top_account_long_short_ratio double precision,
 top_position_long_short_ratio double precision, taker_long_short_ratio double precision,
 funding_rate double precision, funding_interval_hours double precision,
 depth_bands jsonb check(market_governance.remediation_depth_bands_valid_v1(depth_bands)),
 availability_not_before timestamptz,
 availability_basis text,
 record_sha256 bytea not null check(octet_length(record_sha256)=32),
 primary key(source_id,observed_at),
 check(bar_end is null or bar_end>observed_at),
 check((open is null and high is null and low is null and close is null) or
       (num_nonnulls(open,high,low,close)=4 and open>0 and high>0 and low>0 and close>0 and high>=greatest(open,low,close) and low<=least(open,high,close))),
 check(volume is null or volume>=0),
 check(trade_count is null or trade_count>=0),
 check(least(quote_volume,taker_buy_base_volume,taker_buy_quote_volume,open_interest_quantity,open_interest_quote,
 global_account_long_short_ratio,top_account_long_short_ratio,top_position_long_short_ratio,taker_long_short_ratio)>=0),
 check(funding_interval_hours is null or funding_interval_hours>0),
 check(greatest(abs(open),abs(high),abs(low),abs(close),abs(volume),abs(quote_volume),abs(vwap),abs(taker_buy_base_volume),abs(taker_buy_quote_volume),
 abs(open_interest_quantity),abs(open_interest_quote),abs(global_account_long_short_ratio),abs(top_account_long_short_ratio),abs(top_position_long_short_ratio),abs(taker_long_short_ratio),abs(funding_rate),abs(funding_interval_hours))<'Infinity'::float8)
);

create or replace function market_governance.remediation_worker_gate_v1(p_run_id text)
returns jsonb language plpgsql security invoker set search_path=pg_catalog as $$
declare r market_governance.remediation_run_v1%rowtype; used_bytes bigint; limit_bytes bigint;
 wal_now bigint; wal_reset timestamptz; wal_start bigint; wal_limit bigint; wal_growth bigint;
 unbilled_headroom bigint;
begin
 if p_run_id is distinct from 'market_data_remediation_20261008_v1' then raise exception 'remediation_run_not_allowed'; end if;
 select * into strict r from market_governance.remediation_run_v1 where run_id=p_run_id;
 if r.project_ref<>'oxzabweahkoimtevbbny' then raise exception 'remediation_project_mismatch'; end if;
 if r.phase<>3 or r.status ~* '(cancel|stop|complete|closed)' then
  return jsonb_build_object('ready',false,'reason','phase_not_ready','phase',r.phase,'run_status',r.status);
 end if;
 limit_bytes=coalesce((r.protections->'source_acquisition'->>'max_storage_bytes')::bigint,0);
 used_bytes=pg_total_relation_size('market_governance.remediation_source_batch_v1')+
            pg_total_relation_size('market_governance.remediation_source_response_v1')+
            pg_total_relation_size('market_governance.remediation_observation_v1');
 if limit_bytes<=0 or nullif(r.protections->'source_acquisition'->>'price_evidence','') is null then
  return jsonb_build_object('ready',false,'reason','priced_storage_budget_required','used_bytes',used_bytes);
 end if;
 select wal_bytes::bigint,stats_reset into wal_now,wal_reset from pg_stat_wal;
 wal_start=(r.protections->'source_acquisition'->>'wal_start_bytes')::bigint;
 wal_limit=(r.protections->'source_acquisition'->>'max_wal_growth_bytes')::bigint;
 if wal_start is null or wal_limit is null or wal_limit<=0 or wal_reset is distinct from
 nullif(r.protections->'source_acquisition'->>'wal_stats_reset','')::timestamptz or wal_now<wal_start then
  return jsonb_build_object('ready',false,'reason','wal_baseline_required_or_reset','used_bytes',used_bytes);
 end if;
 wal_growth=wal_now-wal_start;
 if wal_growth+33554432>=wal_limit then
  return jsonb_build_object('ready',false,'reason','global_wal_growth_ceiling_reached','used_bytes',used_bytes,'wal_growth_bytes',wal_growth,'max_wal_growth_bytes',wal_limit);
 end if;
 -- Public pricing is not authorization for extra charges. Bulk acquisition must
 -- fit measured space before the current allocated disk's autoscale threshold.
 unbilled_headroom=(r.protections->'source_acquisition'->>'verified_bytes_before_storage_autoscale')::bigint;
 if unbilled_headroom is null or unbilled_headroom<=0 or
 nullif(r.protections->'source_acquisition'->>'existing_storage_headroom_evidence','') is null then
  return jsonb_build_object('ready',false,'reason','verified_existing_unbilled_storage_headroom_required','used_bytes',used_bytes,'wal_growth_bytes',wal_growth);
 end if;
 if used_bytes+wal_growth+33554432>=unbilled_headroom then
  return jsonb_build_object('ready',false,'reason','existing_unbilled_storage_headroom_ceiling_reached','used_bytes',used_bytes,'wal_growth_bytes',wal_growth,'verified_bytes_before_storage_autoscale',unbilled_headroom);
 end if;
 if used_bytes+16777216>=limit_bytes then
  return jsonb_build_object('ready',false,'reason','storage_budget_reached','used_bytes',used_bytes,'max_bytes',limit_bytes);
 end if;
 return jsonb_build_object('ready',true,'used_bytes',used_bytes,'max_bytes',limit_bytes,'wal_growth_bytes',wal_growth,'max_wal_growth_bytes',wal_limit,'verified_bytes_before_storage_autoscale',unbilled_headroom,'phase',r.phase);
end $$;

create or replace function market_governance.remediation_store_source_v1(p_batch_id bigint,p_source jsonb)
returns uuid language plpgsql security invoker set search_path=pg_catalog as $$
declare sid uuid; packed bytea; h bytea; existing market_governance.remediation_source_response_v1%rowtype;
begin
 sid=(p_source->>'source_id')::uuid;
 if sid is null then raise exception 'source_id_required'; end if;
 packed=decode(p_source->>'compressed_base64','base64');
 h=sha256(packed);
 if encode(h,'hex')<>p_source->>'compressed_sha256' then raise exception 'compressed_source_sha_mismatch'; end if;
 if exists(select 1 from jsonb_object_keys(coalesce(p_source->'headers','{}'::jsonb)) k where lower(k) in ('authorization','apikey','api-key','cookie','set-cookie','x-astra-token')) then
  raise exception 'sensitive_source_header_rejected';
 end if;
 insert into market_governance.remediation_source_response_v1(
 source_id,batch_id,role,source_url,http_status,response_headers,received_at,revision_at,
 source_sha256,stored_body_sha256,compressed_sha256,original_bytes,compressed_body,storage_encoding,parser_version,credential_redactions,provenance)
 values(sid,p_batch_id,p_source->>'role',p_source->>'source_url',(p_source->>'http_status')::integer,
 coalesce(p_source->'headers','{}'::jsonb),(p_source->>'received_at')::timestamptz,nullif(p_source->>'revision_at','')::timestamptz,
 decode(p_source->>'source_sha256','hex'),decode(p_source->>'stored_body_sha256','hex'),h,(p_source->>'original_bytes')::bigint,packed,'gzip',
 p_source->>'parser_version',coalesce((p_source->>'credential_redactions')::integer,0),coalesce(p_source->'provenance','{}'::jsonb))
 on conflict(source_id) do nothing;
 select * into strict existing from market_governance.remediation_source_response_v1 where source_id=sid;
 if existing.batch_id<>p_batch_id or existing.compressed_sha256<>h then raise exception 'source_version_conflict'; end if;
 return sid;
end $$;

create or replace function public.market_data_remediation_claim_v1(p_request jsonb)
returns jsonb language plpgsql security invoker set search_path=pg_catalog as $$
declare rid text=p_request->>'run_id'; wid text=p_request->>'worker_id'; g jsonb; q market_governance.remediation_source_batch_v1%rowtype;
begin
 g=market_governance.remediation_worker_gate_v1(rid);
 if not (g->>'ready')::boolean then return g||jsonb_build_object('status','idle'); end if;
 if wid is null or length(wid)>160 then raise exception 'worker_identity_required'; end if;
 perform pg_advisory_xact_lock(hashtextextended(rid||':source_claim',0));
 update market_governance.remediation_source_batch_v1 set status=case when attempts>=3 then 'FAILED' else 'RETRY' end,
 attempt_history=attempt_history||jsonb_build_array(jsonb_build_object('attempt',attempts,'status',case when attempts>=3 then 'FAILED' else 'RETRY' end,
 'source_id',current_source_id,'acquired_count',acquired_count,'valid_count',valid_count,'invalid_count',invalid_count,
 'duplicate_count',duplicate_count,'outside_count',outside_count,'validation',validation,'error',jsonb_build_object('code','expired_worker_lease'),'completed_at',clock_timestamp())),
 last_error=jsonb_build_object('code','expired_worker_lease'),worker_id=null,lease_token=null,lease_expires_at=null,updated_at=clock_timestamp()
 where run_id=rid and status='RUNNING' and lease_expires_at<clock_timestamp();
 if exists(select 1 from market_governance.remediation_source_batch_v1 where run_id=rid and status='RUNNING' and lease_expires_at>=clock_timestamp()) then
  return g||jsonb_build_object('status','idle','reason','existing_source_lease');
 end if;
 select * into q from market_governance.remediation_source_batch_v1
 where run_id=rid and status in ('QUEUED','RETRY') and attempts<3 and not_before<=clock_timestamp()
 order by priority desc,batch_id for update skip locked limit 1;
 if not found then return g||jsonb_build_object('status','idle','reason','no_ready_batches'); end if;
 update market_governance.remediation_source_batch_v1 set status='RUNNING',attempts=attempts+1,worker_id=wid,
 lease_token=gen_random_uuid(),lease_expires_at=clock_timestamp()+interval '3 minutes',heartbeat_at=clock_timestamp(),
 current_source_id=null,acquired_count=0,valid_count=0,invalid_count=0,duplicate_count=0,outside_count=0,
 validation='{}'::jsonb,completed_at=null,updated_at=clock_timestamp(),last_error=null where batch_id=q.batch_id returning * into q;
 return g||jsonb_build_object('status','claimed','batch',to_jsonb(q));
end $$;

create or replace function public.market_data_remediation_heartbeat_v1(p_request jsonb)
returns jsonb language plpgsql security invoker set search_path=pg_catalog as $$
declare g jsonb; n integer;
begin
 g=market_governance.remediation_worker_gate_v1(p_request->>'run_id');
 if not (g->>'ready')::boolean then return g||jsonb_build_object('renewed',false); end if;
 update market_governance.remediation_source_batch_v1 set heartbeat_at=clock_timestamp(),lease_expires_at=clock_timestamp()+interval '3 minutes',updated_at=clock_timestamp()
 where batch_id=(p_request->>'batch_id')::bigint and run_id=p_request->>'run_id' and status='RUNNING'
 and lease_token=(p_request->>'lease_token')::uuid and worker_id=p_request->>'worker_id' and lease_expires_at>=clock_timestamp();
 get diagnostics n=row_count;
 return g||jsonb_build_object('renewed',n=1);
end $$;

create or replace function public.market_data_remediation_commit_v1(p_request jsonb)
returns jsonb language plpgsql security invoker set search_path=pg_catalog as $$
declare q market_governance.remediation_source_batch_v1%rowtype; g jsonb; sid uuid; a jsonb; n bigint; v jsonb;
begin
 g=market_governance.remediation_worker_gate_v1(p_request->>'run_id');
 if not (g->>'ready')::boolean then raise exception 'remediation_commit_gate_%',g->>'reason'; end if;
 select * into strict q from market_governance.remediation_source_batch_v1 where batch_id=(p_request->>'batch_id')::bigint and run_id=p_request->>'run_id' for update;
 if q.status in ('COMPLETE','SOURCE_INVALID') and p_request->>'final'='true' and
 q.lease_token=(p_request->>'lease_token')::uuid and q.worker_id=p_request->>'worker_id' and
 q.current_source_id=(p_request->>'source_id')::uuid and q.valid_count=(p_request->'validation'->>'valid_count')::bigint then
 return jsonb_build_object('stored',true,'source_id',q.current_source_id,'valid_count',q.valid_count,'final',true,'replayed',true); end if;
 if q.status<>'RUNNING' or q.lease_token is distinct from (p_request->>'lease_token')::uuid or q.worker_id is distinct from p_request->>'worker_id' or q.lease_expires_at<clock_timestamp() then raise exception 'source_lease_mismatch'; end if;
 if p_request ? 'source' then
  sid=market_governance.remediation_store_source_v1(q.batch_id,p_request->'source');
  if coalesce((p_request->>'artifact_only')::boolean,false) then
   update market_governance.remediation_source_batch_v1 set heartbeat_at=clock_timestamp(),lease_expires_at=clock_timestamp()+interval '3 minutes',
   current_source_id=case when p_request->'source'->>'role'='primary' and p_request->'source'->>'http_status'='200' then sid else current_source_id end where batch_id=q.batch_id;
   return jsonb_build_object('stored',true,'source_id',sid,'artifact_only',true);
  end if;
 else sid=(p_request->>'source_id')::uuid;
 end if;
 if not exists(select 1 from market_governance.remediation_source_response_v1 where source_id=sid and batch_id=q.batch_id and role='primary' and http_status=200) then raise exception 'valid_primary_source_required'; end if;
 a=coalesce(p_request->'records','[]'::jsonb);
 if jsonb_typeof(a)<>'array' or jsonb_array_length(a)>1000 then raise exception 'record_batch_size_invalid'; end if;
 if exists(select 1 from jsonb_array_elements(a) x where x->>'observed_at' is null or jsonb_typeof(x->'values') is distinct from 'object') then raise exception 'record_required_fields_missing'; end if;
 if q.source_type in ('coinbase_candles','twelvedata_candles','massive_candles','binance_klines','binance_mark','binance_index') and
 exists(select 1 from jsonb_array_elements(a) x where x->>'bar_end' is null or
 x->'values'->>'open' is null or x->'values'->>'high' is null or x->'values'->>'low' is null or x->'values'->>'close' is null) then raise exception 'candle_required_fields_missing'; end if;
 if q.source_type in ('binance_mark','binance_index') and exists(select 1 from jsonb_array_elements(a) x where
 x->'values'->>'volume' is not null or x->'values'->>'quote_volume' is not null or x->'values'->>'trade_count' is not null or
 x->'values'->>'taker_buy_base_volume' is not null or x->'values'->>'taker_buy_quote_volume' is not null) then raise exception 'mark_index_trade_activity_not_supported'; end if;
 if q.source_type='binance_book_depth' and exists(select 1 from jsonb_array_elements(a) x where
 x->>'bar_end' is not null or jsonb_typeof(x->'values'->'depth_bands') is distinct from 'array' or x->'values'->>'open' is not null or
 x->'values'->>'close' is not null or x->'values'->>'volume' is not null or x->'values'->>'trade_count' is not null) then raise exception 'source_depth_profile_contract_mismatch'; end if;
 if q.source_type<>'binance_book_depth' and exists(select 1 from jsonb_array_elements(a) x where x->'values'->>'depth_bands' is not null) then raise exception 'source_depth_field_not_allowed'; end if;
 if exists(select 1 from jsonb_array_elements(a) x where (x->>'observed_at')::timestamptz<q.start_ts or (x->>'observed_at')::timestamptz>=q.end_ts or
 (nullif(x->>'bar_end','')::timestamptz is not null and (x->>'bar_end')::timestamptz>q.end_ts)) then raise exception 'record_outside_authorized_batch'; end if;
 if exists(select 1 from jsonb_array_elements(a) x cross join lateral jsonb_each_text(x->'values') m
 where m.value ~* '^[-+]?(nan|infinity|inf)$') then raise exception 'nonfinite_source_value'; end if;
 if exists(select 1 from jsonb_array_elements(a) x join market_governance.remediation_observation_v1 o
 on o.source_id=sid and o.observed_at=(x->>'observed_at')::timestamptz where o.record_sha256<>sha256(convert_to(x::text,'UTF8'))) then raise exception 'normalized_source_version_conflict'; end if;
 if exists(select 1 from jsonb_array_elements(a) x group by (x->>'observed_at')::timestamptz having count(distinct x::text)>1) then raise exception 'within_commit_source_version_conflict'; end if;
 insert into market_governance.remediation_observation_v1(
 source_id,observed_at,bar_end,open,high,low,close,volume,quote_volume,trade_count,vwap,taker_buy_base_volume,taker_buy_quote_volume,
 open_interest_quantity,open_interest_quote,global_account_long_short_ratio,top_account_long_short_ratio,top_position_long_short_ratio,taker_long_short_ratio,
 funding_rate,funding_interval_hours,depth_bands,availability_not_before,availability_basis,record_sha256)
 select sid,(x->>'observed_at')::timestamptz,nullif(x->>'bar_end','')::timestamptz,
 nullif(x->'values'->>'open','')::float8,nullif(x->'values'->>'high','')::float8,nullif(x->'values'->>'low','')::float8,nullif(x->'values'->>'close','')::float8,
 nullif(x->'values'->>'volume','')::float8,nullif(x->'values'->>'quote_volume','')::float8,nullif(x->'values'->>'trade_count','')::bigint,
 nullif(x->'values'->>'vwap','')::float8,nullif(x->'values'->>'taker_buy_base_volume','')::float8,nullif(x->'values'->>'taker_buy_quote_volume','')::float8,
 nullif(x->'values'->>'open_interest_quantity','')::float8,nullif(x->'values'->>'open_interest_quote','')::float8,
 nullif(x->'values'->>'global_account_long_short_ratio','')::float8,nullif(x->'values'->>'top_account_long_short_ratio','')::float8,
 nullif(x->'values'->>'top_position_long_short_ratio','')::float8,nullif(x->'values'->>'taker_long_short_ratio','')::float8,
 nullif(x->'values'->>'funding_rate','')::float8,nullif(x->'values'->>'funding_interval_hours','')::float8,
 x->'values'->'depth_bands',
 nullif(x->'values'->>'availability_not_before','')::timestamptz,nullif(x->'values'->>'availability_basis',''),sha256(convert_to(x::text,'UTF8'))
 from jsonb_array_elements(a) x on conflict(source_id,observed_at) do nothing;
 select count(*) into n from market_governance.remediation_observation_v1 where source_id=sid;
 v=coalesce(p_request->'validation','{}'::jsonb);
 if coalesce((p_request->>'final')::boolean,false) then
  if exists(select 1 from (values ('raw_count'),('valid_count'),('invalid_count'),('duplicate_count'),('outside_count')) k(name)
  where nullif(v->>k.name,'') is null or (v->>k.name)::bigint<0) then raise exception 'final_validation_counts_required'; end if;
  if jsonb_typeof(v->'normalization_passed') is distinct from 'boolean' then raise exception 'final_validation_status_required'; end if;
  if n<>coalesce((v->>'valid_count')::bigint,-1) then raise exception 'final_valid_count_mismatch'; end if;
  if (v->>'raw_count')::bigint<>n+coalesce((v->>'invalid_count')::bigint,0)+coalesce((v->>'duplicate_count')::bigint,0)+coalesce((v->>'outside_count')::bigint,0) then raise exception 'final_source_population_mismatch'; end if;
 end if;
 update market_governance.remediation_source_batch_v1 set current_source_id=sid,valid_count=n,heartbeat_at=clock_timestamp(),
 lease_expires_at=clock_timestamp()+interval '3 minutes',updated_at=clock_timestamp(),
 acquired_count=case when p_request ? 'validation' then (v->>'raw_count')::bigint else acquired_count end,
 invalid_count=case when p_request ? 'validation' then coalesce((v->>'invalid_count')::bigint,0) else invalid_count end,
 duplicate_count=case when p_request ? 'validation' then coalesce((v->>'duplicate_count')::bigint,0) else duplicate_count end,
 outside_count=case when p_request ? 'validation' then coalesce((v->>'outside_count')::bigint,0) else outside_count end,
 validation=case when p_request ? 'validation' then v else validation end,
 attempt_history=case when p_request->>'final'='true' then attempt_history||jsonb_build_array(jsonb_build_object('attempt',attempts,
 'status',case when coalesce((v->>'invalid_count')::bigint,0)>0 or coalesce((v->>'duplicate_conflict_count')::bigint,0)>0 or not coalesce((v->>'normalization_passed')::boolean,false) then 'SOURCE_INVALID' else 'COMPLETE' end,
 'source_id',sid,'acquired_count',(v->>'raw_count')::bigint,'valid_count',n,'invalid_count',coalesce((v->>'invalid_count')::bigint,0),
 'duplicate_count',coalesce((v->>'duplicate_count')::bigint,0),'outside_count',coalesce((v->>'outside_count')::bigint,0),'validation',v,'completed_at',clock_timestamp())) else attempt_history end,
 status=case when p_request->>'final'='true' then case when coalesce((v->>'invalid_count')::bigint,0)>0 or coalesce((v->>'duplicate_conflict_count')::bigint,0)>0 or not coalesce((v->>'normalization_passed')::boolean,false) then 'SOURCE_INVALID' else 'COMPLETE' end else status end,
 completed_at=case when p_request->>'final'='true' then clock_timestamp() else completed_at end
 where batch_id=q.batch_id;
 return jsonb_build_object('stored',true,'source_id',sid,'valid_count',n,'final',coalesce((p_request->>'final')::boolean,false));
end $$;

create or replace function public.market_data_remediation_fail_v1(p_request jsonb)
returns jsonb language plpgsql security invoker set search_path=pg_catalog as $$
declare q market_governance.remediation_source_batch_v1%rowtype; sid uuid; st text; retry_seconds integer;
begin
 if p_request->>'run_id' is distinct from 'market_data_remediation_20261008_v1' then raise exception 'remediation_run_not_allowed'; end if;
 select * into strict q from market_governance.remediation_source_batch_v1 where batch_id=(p_request->>'batch_id')::bigint and run_id=p_request->>'run_id' for update;
 if q.status<>'RUNNING' or q.lease_token is distinct from (p_request->>'lease_token')::uuid or q.worker_id is distinct from p_request->>'worker_id' then raise exception 'source_lease_mismatch'; end if;
 if p_request ? 'source' then sid=market_governance.remediation_store_source_v1(q.batch_id,p_request->'source'); end if;
 st=case when p_request->>'retryable'='true' and q.attempts<3 then 'RETRY'
         when p_request->>'source_invalid'='true' then 'SOURCE_INVALID'
         when p_request->>'blocked_external'='true' then 'BLOCKED' else 'FAILED' end;
 retry_seconds=least(3600,greatest(20,coalesce((p_request->>'retry_after_seconds')::integer,60)));
 update market_governance.remediation_source_batch_v1 set status=st,not_before=clock_timestamp()+retry_seconds*interval '1 second',
 attempt_history=attempt_history||jsonb_build_array(jsonb_build_object('attempt',attempts,'status',st,'source_id',coalesce(sid,current_source_id),
 'acquired_count',acquired_count,'valid_count',valid_count,'invalid_count',invalid_count,'duplicate_count',duplicate_count,'outside_count',outside_count,
 'validation',validation,'error',coalesce(p_request->'error','{"code":"unspecified_source_error"}'::jsonb),'completed_at',clock_timestamp())),
 last_error=coalesce(p_request->'error','{"code":"unspecified_source_error"}'::jsonb),heartbeat_at=clock_timestamp(),updated_at=clock_timestamp(),
 lease_token=null,lease_expires_at=null,completed_at=case when st='RETRY' then null else clock_timestamp() end where batch_id=q.batch_id;
 return jsonb_build_object('stored',true,'status',st,'source_id',sid);
end $$;

alter table market_governance.remediation_source_batch_v1 enable row level security;
alter table market_governance.remediation_source_response_v1 enable row level security;
alter table market_governance.remediation_observation_v1 enable row level security;
revoke all on market_governance.remediation_source_batch_v1,market_governance.remediation_source_response_v1,market_governance.remediation_observation_v1 from public,anon,authenticated;
revoke all on market_governance.remediation_source_batch_v1,market_governance.remediation_source_response_v1,market_governance.remediation_observation_v1 from service_role;
grant usage on schema market_governance to service_role;
grant select on market_governance.remediation_run_v1 to service_role;
grant select,update on market_governance.remediation_source_batch_v1 to service_role;
grant select,insert on market_governance.remediation_source_response_v1,market_governance.remediation_observation_v1 to service_role;
revoke all on function market_governance.remediation_worker_gate_v1(text),market_governance.remediation_store_source_v1(bigint,jsonb) from public,anon,authenticated;
grant execute on function market_governance.remediation_worker_gate_v1(text),market_governance.remediation_store_source_v1(bigint,jsonb) to service_role;
revoke all on function market_governance.remediation_depth_bands_valid_v1(jsonb) from public,anon,authenticated;
grant execute on function market_governance.remediation_depth_bands_valid_v1(jsonb) to service_role;
revoke all on function public.market_data_remediation_claim_v1(jsonb),public.market_data_remediation_heartbeat_v1(jsonb),public.market_data_remediation_commit_v1(jsonb),public.market_data_remediation_fail_v1(jsonb) from public,anon,authenticated;
grant execute on function public.market_data_remediation_claim_v1(jsonb),public.market_data_remediation_heartbeat_v1(jsonb),public.market_data_remediation_commit_v1(jsonb),public.market_data_remediation_fail_v1(jsonb) to service_role;
comment on table market_governance.remediation_observation_v1 is 'Compact source-versioned remediation observations. Staged until coordinator verification. availability_not_before is only a source timing bound, never observed publication/receipt. No automatic canonical promotion.';
comment on table market_governance.remediation_source_response_v1 is 'Immutable gzip source responses, original/stored/compressed SHA256 and actual acquisition receipt. Credential redaction, if any, is explicit; original body hash is retained.';
commit;
