-- Reusable findings discovered while hardening the Pro research operating model.
-- They are propagated through the canonical context pack so specialist workstreams
-- do not rediscover or silently violate these data contracts.

insert into research_hub.research_findings(finding_key,finding_type,title,statement,status,evidence,source_run_keys,source_candidate_ids,reusable,propagation_targets)
values
('CRYPTO-BOOKFIX-POSTCUTOVER-V1','data_quality','Historical Binance futures book state quarantined; post-fix sample is clean','Pre-fix Binance futures partial-depth state produced crossed/stale books and must not be used for promotion-grade spread/depth research. The corrected collector treats depth20 messages as full partial-book snapshots and discards crossed books. Future microstructure research must use the prospective clean-book source after 2026-08-11 23:30 UTC and pass a seven-day quality gate.','active',jsonb_build_object('clean_dataset_key','primary.crypto_microstructure_valid_book_postfix_v1','historical_rows_quarantined',true),array[]::text[],array[]::text[],true,array['ARCH-PRO','QUOTE-TRADE','METHOD','EXEC-SIGNAL']),
('CRYPTO-CROSSVENUE-SIGN-CONTRACT-V1','methodology','Cross-venue price-gap sign made explicit','The legacy public.crypto_research_crossvenue_1m log_ratio uses the opposite sign to ln(Binance close / Coinbase close) in a verified BTC spot-check. New research ignores legacy log_ratio and uses explicit named formulas. The June-July synchronized window is adaptive-reuse discovery/validation only and cannot provide untouched promotion evidence.','active',jsonb_build_object('feature_set_key','crypto.crossvenue.sync.v1','promotion_requires_future_replication',true,'legacy_log_ratio_ignored',true),array[]::text[],array[]::text[],true,array['ARCH-PRO','XAL','METHOD','EXEC-SIGNAL'])
on conflict(finding_key) do update set finding_type=excluded.finding_type,title=excluded.title,statement=excluded.statement,status=excluded.status,evidence=excluded.evidence,reusable=excluded.reusable,propagation_targets=excluded.propagation_targets,updated_at=now();

insert into research_hub.program_jobs(job_key,exact_name,purpose,store_key,source_schema,source_table,source_id,job_kind,current_state,started_at,latest_successful_checkpoint,progress_current,progress_total,completion_pct,latest_result,current_error,retry_state,next_automatic_action,intervention_required,exact_intervention,frozen_rule,holdout_sensitive,metadata)
values('METHOD-BINANCE-DERIV-OBSERVABILITY-V1','Binance derivatives historical observability contract','Freeze point-in-time observability semantics for historical Binance funding, open-interest, long/short positioning and taker-ratio timestamps before enabling derivatives feature materialisation.','market_data_primary','public','crypto_derivatives_metrics','binance-futures-historical-metrics','methodology_data_contract','blocked_temporal_contract_review',now(),now(),0,1,0,jsonb_build_object('available_rows_15m',678912,'funding_rows',28701,'symbols',26,'coverage_start','2025-10-01T00:00:00Z','coverage_end','2026-06-30T23:45:00Z'),null,'not an infrastructure failure; conservative methodology block','Verify endpoint-specific sampling-period/timestamp semantics from authoritative Binance documentation or payload timing tests. Define observable_at for each metric family before registering any point-in-time derivatives feature set. Do not infer bucket availability from timestamp alone.',false,null,true,true,jsonb_build_object('user_action_required',false,'do_not_materialize_until_resolved',true,'metric_families',array['funding','open_interest','global_long_short_ratio','top_account_long_short_ratio','top_position_long_short_ratio','taker_buy_sell_ratio']))
on conflict(job_key) do update set current_state=excluded.current_state,latest_result=excluded.latest_result,current_error=null,retry_state=excluded.retry_state,next_automatic_action=excluded.next_automatic_action,metadata=excluded.metadata,updated_at=now();