-- Freeze specialist statistical, placebo and structural-event vocabulary before
-- the first cross-venue screen. The June/July window is adaptive-reuse only.
insert into research_hub.statistical_test_profiles(profile_key,description,test_spec,promotion_gate,enabled,version)
values('crypto_crossvenue_v1','Frozen evaluation profile for synchronized Binance/Coinbase leader/follower discovery on an adaptive-reuse historical sample.',
jsonb_build_object('screening',jsonb_build_object('global_bh_fdr_q',0.05,'direction_inference','two_sided_when_direction_selected_from_discovery','tail_quantiles',jsonb_build_array(0.02,0.05,0.10,0.20),'screening_round_trip_cost_bps',20),'lag_family_minutes',jsonb_build_array(1,2,5,10,15,30),'placebo_controls',jsonb_build_array('time_shuffle','symbol_permutation','reverse_venue_role'),'dependence_tests',jsonb_build_array('UTC_date_cluster_bootstrap','moving_block_bootstrap_6h','moving_block_bootstrap_24h'),'cost_stress_bps',jsonb_build_array(20,50,100),'required_breakdowns',jsonb_build_array('symbol','venue_target','UTC_day','hour_of_day','weekday_weekend','volatility_regime','signal_magnitude'),'concentration_tests',jsonb_build_array('best_5pct_trades','best_10_trades','single_symbol','single_UTC_day'),'adaptive_reuse',true,'historical_window_role','discovery_validation_only','future_replication_required',true),
jsonb_build_object('historical_window_cannot_promote',true,'future_post_definition_replication_required',true,'minimum_future_replication_dates',14,'positive_net_expectancy_at_bps',50,'profit_factor_min_at_50bps',1.2,'positive_at_100bps_stress',true,'placebo_family_must_fail_to_reproduce_edge',true,'dependence_adjusted_ci_lower_mean_gt',0,'parameter_neighbour_positive_fraction_min',0.7,'edge_direction_stable_across_adjacent_lags',true,'no_single_symbol_or_day_dominance',true,'execution_definition_required_before_holdout',true),true,1)
on conflict(profile_key) do update set description=excluded.description,test_spec=excluded.test_spec,promotion_gate=excluded.promotion_gate,enabled=true,version=excluded.version,updated_at=now();

insert into research_hub.event_definitions(event_key,event_version,description,source_feature_set_key,condition_spec,decision_time_rule,available_at_rule,point_in_time_safe,enabled,definition_hash,metadata)
values
('cv.binance_lead_sign_v1',1,'Binance current 1m return exceeds Coinbase current 1m return.','crypto.crossvenue.sync.v1',jsonb_build_object('feature','cv.return_gap_1m_bc','operator','>','threshold',0),'event_ts=decision_ts','available_at=decision_ts',true,true,encode(digest('cv.binance_lead_sign_v1|cv.return_gap_1m_bc>0','sha256'),'hex'),jsonb_build_object('family','leader_sign','threshold_data_independent',true)),
('cv.coinbase_lead_sign_v1',1,'Coinbase current 1m return exceeds Binance current 1m return.','crypto.crossvenue.sync.v1',jsonb_build_object('feature','cv.return_gap_1m_bc','operator','<','threshold',0),'event_ts=decision_ts','available_at=decision_ts',true,true,encode(digest('cv.coinbase_lead_sign_v1|cv.return_gap_1m_bc<0','sha256'),'hex'),jsonb_build_object('family','leader_sign','threshold_data_independent',true)),
('cv.gap_acceleration_v1',1,'Current venue-return gap keeps the prior sign and increases in absolute magnitude.','crypto.crossvenue.sync.v1',jsonb_build_object('all',jsonb_build_array(jsonb_build_object('expression','sign(cv.return_gap_1m_bc)=sign(cv.return_gap_lag1m_bc)'),jsonb_build_object('expression','abs(cv.return_gap_1m_bc)>abs(cv.return_gap_lag1m_bc)'))),'event_ts=decision_ts','available_at=decision_ts',true,true,encode(digest('cv.gap_acceleration_v1|same_sign|abs_current_gt_abs_lag1','sha256'),'hex'),jsonb_build_object('family','sequence','uses_only_current_and_prior_completed_bars',true)),
('cv.gap_flip_v1',1,'Binance/Coinbase 1m return-gap leadership flips sign versus the prior minute.','crypto.crossvenue.sync.v1',jsonb_build_object('expression','cv.return_gap_1m_bc*cv.return_gap_lag1m_bc<0'),'event_ts=decision_ts','available_at=decision_ts',true,true,encode(digest('cv.gap_flip_v1|current_gap*lag1_gap<0','sha256'),'hex'),jsonb_build_object('family','sequence','uses_only_current_and_prior_completed_bars',true)),
('cv.binance_volume_confirms_v1',1,'Binance leads on return and has the stronger current-vs-prior volume shock.','crypto.crossvenue.sync.v1',jsonb_build_object('all',jsonb_build_array(jsonb_build_object('feature','cv.return_gap_1m_bc','operator','>','threshold',0),jsonb_build_object('feature','cv.volume_shock_gap_5m_bc','operator','>','threshold',0))),'event_ts=decision_ts','available_at=decision_ts',true,true,encode(digest('cv.binance_volume_confirms_v1|return_gap>0|volume_shock_gap>0','sha256'),'hex'),jsonb_build_object('family','interaction','threshold_data_independent',true)),
('cv.coinbase_volume_confirms_v1',1,'Coinbase leads on return and has the stronger current-vs-prior volume shock.','crypto.crossvenue.sync.v1',jsonb_build_object('all',jsonb_build_array(jsonb_build_object('feature','cv.return_gap_1m_bc','operator','<','threshold',0),jsonb_build_object('feature','cv.volume_shock_gap_5m_bc','operator','<','threshold',0))),'event_ts=decision_ts','available_at=decision_ts',true,true,encode(digest('cv.coinbase_volume_confirms_v1|return_gap<0|volume_shock_gap<0','sha256'),'hex'),jsonb_build_object('family','interaction','threshold_data_independent',true))
on conflict(event_key) do update set event_version=excluded.event_version,description=excluded.description,source_feature_set_key=excluded.source_feature_set_key,condition_spec=excluded.condition_spec,decision_time_rule=excluded.decision_time_rule,available_at_rule=excluded.available_at_rule,point_in_time_safe=true,enabled=true,definition_hash=excluded.definition_hash,metadata=excluded.metadata,updated_at=now();

update research_hub.program_jobs set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('statistical_profile_key','crypto_crossvenue_v1','frozen_event_keys',jsonb_build_array('cv.binance_lead_sign_v1','cv.coinbase_lead_sign_v1','cv.gap_acceleration_v1','cv.gap_flip_v1','cv.binance_volume_confirms_v1','cv.coinbase_volume_confirms_v1')),updated_at=now() where job_key='FEATURE-CROSSVENUE-LAG-V1';